import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/Footer';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const tiempos = localFont({
  src: './fonts/tiempos.woff2',
  display: 'swap',
  variable: '--font-tiempos-serif', // This defines the CSS variable
});

import { AuthProvider } from '@/components/providers/auth-provider';
import { Toaster } from '@/components/ui/sonner';

// ... (rest of the imports)

// ... (font definitions)

export const metadata: Metadata = {
  title: 'Gold Nexus',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tiempos.variable} antialiased`}
      >
        <AuthProvider>
          <NuqsAdapter>
            <Navbar />
            {children}
            <Footer />
            <Toaster position="top-right" richColors theme="light" />
          </NuqsAdapter>
        </AuthProvider>
      </body>
    </html>
  );
}
